name: build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build image
        run: docker build -t udm-dafni .

      - name: test
        run: docker run -v $PWD/data:/data --name udm-dafni udm-dafni
